using NotesApp.Domain.Common;
using System;
using System.Collections.Generic;
using System.Text;

namespace NotesApp.Domain.Entities
{
    /// <summary>
    /// A note attached to a specific day in the calendar.
    /// Invariants:
    /// - UserId must be non-empty.
    /// - A note must have at least a title OR some content.
    /// </summary>
    public sealed class Note : Entity<Guid>, ICalendarEntity
    {
        // ENTITY CONSTANTS 
        public const int MaxTitleLength = 200;

        /// <summary>
        /// Owner of this note (also our tenant boundary).
        /// </summary>
        public Guid UserId { get; private set; }

        /// <summary>
        /// Date this note is associated with in the calendar.
        /// </summary>
        public DateOnly Date { get; private set; }

        public string Title { get; private set; } = string.Empty;
        public string Content { get; private set; } = string.Empty;

        /// <summary>
        /// Generated by AI later (summaries, tags, etc.).
        /// </summary>
        public string? Summary { get; private set; }
        public string? Tags { get; private set; }

        public long Version { get; private set; } = 1;

        // EF Core constructor
        private Note()
        {
        }

        private Note(Guid id,
                 Guid userId,
                 DateOnly date,
                 string title,
                 string content,
                 string? summary,
                 string? tags,
                 DateTime utcNow)
        : base(id, utcNow)
        {
            UserId = userId;
            Date = date;
            Title = title;
            Content = content;
            Summary = summary;
            Tags = tags;
            Version = 1;
        }

        // FACTORY

        public static DomainResult<Note> Create(Guid userId,
                                            DateOnly date,
                                            string? title,
                                            string? content,
                                            string? summary,
                                            string? tags,
                                            DateTime utcNow)
        {
            var errors = new List<DomainError>();

            var normalizedTitle = title?.Trim() ?? string.Empty;
            var normalizedContent = content?.Trim() ?? string.Empty;
            var normalizedSummary = summary?.Trim();
            var normalizedTags = tags?.Trim();

            if (userId == Guid.Empty)
            {
                errors.Add(new DomainError("Note.UserId.Empty", "UserId must be a non-empty GUID."));
            }

            if (date == default)
            {
                errors.Add(new DomainError("Note.Date.Default", "Date must be a valid calendar date."));
            }

            // Invariant: at least title or content must have data
            if (normalizedTitle.Length == 0 && normalizedContent.Length == 0)
            {
                errors.Add(new DomainError("Note.Empty", "Note must have at least a title or some content."));
            }

            if (errors.Count > 0)
            {
                return DomainResult<Note>.Failure(errors);
            }

            var id = Guid.NewGuid();
            var note = new Note(id,
                                userId,
                                date,
                                normalizedTitle,
                                normalizedContent,
                                normalizedSummary,
                                normalizedTags,
                                utcNow);

            return DomainResult<Note>.Success(note);
        }

        // BEHAVIOURS

        public DomainResult Update(string? title,
                                   string? content,
                                   string? summary,
                                   string? tags,
                                   DateOnly date,
                                   DateTime utcNow)
        {
            if (IsDeleted)
            {
                return DomainResult.Failure(
                    new DomainError("Note.Deleted", "Cannot update a deleted note.")
                );
            }

            var errors = new List<DomainError>();

            var normalizedTitle = title?.Trim() ?? string.Empty;
            var normalizedContent = content?.Trim() ?? string.Empty;
            var normalizedSummary = summary?.Trim();
            var normalizedTags = tags?.Trim();

            // Same invariant as Create
            if (normalizedTitle.Length == 0 && normalizedContent.Length == 0)
            {
                errors.Add(new DomainError("Note.Empty", "Note must have at least a title or some content."));
            }

            if (date == default)
            {
                errors.Add(new DomainError("Note.Date.Default", "Date must be a valid calendar date."));
            }

            if (errors.Count > 0)
            {
                return DomainResult.Failure(errors);
            }

            Title = normalizedTitle;
            Content = normalizedContent;
            Summary = normalizedSummary;
            Tags = normalizedTags;
            Date = date;

            IncrementVersion();
            Touch(utcNow);

            return DomainResult.Success();
        }


        /// <summary>
        /// Move the note to another day (e.g. user drags it to another date).
        /// </summary>
        public DomainResult MoveToDate(DateOnly newDate, DateTime utcNow)
        {
            if (IsDeleted)
            {
                return DomainResult.Failure(
                    new DomainError("Note.Deleted", "Cannot move a deleted note.")
                );
            }

            if (newDate == default)
            {
                return DomainResult.Failure(
                    new DomainError("Note.Date.Default", "Date must be a valid calendar date.")
                );
            }

            if (Date != newDate)
            {
                Date = newDate;
                IncrementVersion();
                Touch(utcNow);
            }

            return DomainResult.Success();
        }


        public DomainResult SoftDelete(DateTime utcNow)
        {
            if (IsDeleted)
            {
                // Idempotent: deleting twice is still success
                return DomainResult.Success();
            }

            MarkDeleted(utcNow);
            IncrementVersion();
            return DomainResult.Success();
        }

        public DomainResult RestoreNote(DateTime utcNow)
        {
            if (!IsDeleted)
            {
                // Idempotent: restoring non-deleted is OK
                return DomainResult.Success();
            }

            Restore(utcNow);
            IncrementVersion();
            return DomainResult.Success();
        }

        /// <summary>
        /// Convenience helper for UI: derive a display title.
        /// (No side-effects, purely read-only.)
        /// </summary>
        public string GetDisplayTitle()
        {
            if (!string.IsNullOrWhiteSpace(Title))
            {
                return Title;
            }

            if (!string.IsNullOrWhiteSpace(Content))
            {
                const int max = 30;
                return Content.Length <= max ? Content : Content[..max] + "…";
            }

            return "Untitled note";
        }

        // TODO : For Ai Later
        public DomainResult SetSummaryAndTags(string? summary, string? tags, DateTime utcNow)
        {
            if (IsDeleted)
            {
                return DomainResult.Failure(
                    new DomainError("Note.Deleted", "Cannot set summary on a deleted note.")
                );
            }

            Summary = summary;
            Tags = tags;
            IncrementVersion();
            Touch(utcNow);

            return DomainResult.Success();
        }

        private void IncrementVersion()
        {
            Version++;
        }
    }
}
