using NotesApp.Domain.Common;
using System;
using System.Collections.Generic;
using System.Text;

namespace NotesApp.Domain.Entities
{
    /// A note attached to a specific day in the calendar.
    /// 
    /// BLOCK-BASED CONTENT MODEL:
    /// Note no longer stores content directly. Instead, content is stored as
    /// a collection of Block entities that reference this Note as their parent.
    /// This enables:
    /// - Fine-grained sync (each block syncs independently)
    /// - Rich content types (paragraphs, images, headings, etc.)
    /// - Better conflict resolution (per-block instead of whole-content)
    /// 
    /// Invariants:
    /// - UserId must be non-empty.
    /// - Title is required (non-empty) since content is now in blocks.
    public sealed class Note : Entity<Guid>, ICalendarEntity
    {
        // ENTITY CONSTANTS 
        public const int MaxTitleLength = 200;

        /// <summary>
        /// Owner of this note (also our tenant boundary).
        /// </summary>
        public Guid UserId { get; private set; }

        /// <summary>
        /// Date this note is associated with in the calendar.
        /// </summary>
        public DateOnly Date { get; private set; }

        public string Title { get; private set; } = string.Empty;


        /// <summary>
        /// Generated by AI later (summaries, tags, etc.).
        /// </summary>
        public string? Summary { get; private set; }
        public string? Tags { get; private set; }

        public long Version { get; private set; } = 1;

        // EF Core constructor
        private Note()
        {
        }

        private Note(Guid id,
                 Guid userId,
                 DateOnly date,
                 string title,
                 string? summary,
                 string? tags,
                 DateTime utcNow)
        : base(id, utcNow)
        {
            UserId = userId;
            Date = date;
            Title = title;
            Summary = summary;
            Tags = tags;
            Version = 1;
        }

        // FACTORY

        /// <summary>
        /// Creates a new Note.
        /// 
        /// CHANGED: Content parameter removed. Title is now required.
        /// Content should be added as Block entities after Note creation.
        /// </summary>
        public static DomainResult<Note> Create(Guid userId,
                                             DateOnly date,
                                             string? title,
                                             string? summary,
                                             string? tags,
                                             DateTime utcNow)
        {
            var errors = new List<DomainError>();

            var normalizedTitle = title?.Trim() ?? string.Empty;
            var normalizedSummary = summary?.Trim();
            var normalizedTags = tags?.Trim();

            if (userId == Guid.Empty)
            {
                errors.Add(new DomainError("Note.UserId.Empty", "UserId must be a non-empty GUID."));
            }

            if (date == default)
            {
                errors.Add(new DomainError("Note.Date.Default", "Date must be a valid calendar date."));
            }

            // ─────────────────────────────────────────────────────────────────
            // CHANGED: Title is now required (content is in blocks)
            // ─────────────────────────────────────────────────────────────────
            if (normalizedTitle.Length == 0)
            {
                errors.Add(new DomainError("Note.Title.Empty", "Note title is required."));
            }

            if (normalizedTitle.Length > MaxTitleLength)
            {
                errors.Add(new DomainError("Note.Title.TooLong", $"Title cannot exceed {MaxTitleLength} characters."));
            }

            if (errors.Count > 0)
            {
                return DomainResult<Note>.Failure(errors);
            }

            var id = Guid.NewGuid();
            var note = new Note(id,
                                userId,
                                date,
                                normalizedTitle,
                                normalizedSummary,
                                normalizedTags,
                                utcNow);

            return DomainResult<Note>.Success(note);
        }

        // BEHAVIOURS

        /// <summary>
        /// Updates the note's metadata.
        /// 
        /// CHANGED: Content parameter removed. Content updates happen via Block entities.
        /// </summary>
        public DomainResult Update(string? title,
                                   string? summary,
                                   string? tags,
                                   DateOnly date,
                                   DateTime utcNow)
        {
            if (IsDeleted)
            {
                return DomainResult.Failure(
                    new DomainError("Note.Deleted", "Cannot update a deleted note.")
                );
            }

            var errors = new List<DomainError>();

            var normalizedTitle = title?.Trim() ?? string.Empty;
            var normalizedSummary = summary?.Trim();
            var normalizedTags = tags?.Trim();

            // ─────────────────────────────────────────────────────────────────
            // CHANGED: Title is now required
            // ─────────────────────────────────────────────────────────────────
            if (normalizedTitle.Length == 0)
            {
                errors.Add(new DomainError("Note.Title.Empty", "Note title is required."));
            }

            if (normalizedTitle.Length > MaxTitleLength)
            {
                errors.Add(new DomainError("Note.Title.TooLong", $"Title cannot exceed {MaxTitleLength} characters."));
            }

            if (date == default)
            {
                errors.Add(new DomainError("Note.Date.Default", "Date must be a valid calendar date."));
            }

            if (errors.Count > 0)
            {
                return DomainResult.Failure(errors);
            }

            Title = normalizedTitle;
            Summary = normalizedSummary;
            Tags = normalizedTags;
            Date = date;

            IncrementVersion();
            Touch(utcNow);

            return DomainResult.Success();
        }


        /// <summary>
        /// Move the note to another day (e.g. user drags it to another date).
        /// </summary>
        public DomainResult MoveToDate(DateOnly newDate, DateTime utcNow)
        {
            if (IsDeleted)
            {
                return DomainResult.Failure(
                    new DomainError("Note.Deleted", "Cannot move a deleted note.")
                );
            }

            if (newDate == default)
            {
                return DomainResult.Failure(
                    new DomainError("Note.Date.Default", "Date must be a valid calendar date.")
                );
            }

            if (Date != newDate)
            {
                Date = newDate;
                IncrementVersion();
                Touch(utcNow);
            }

            return DomainResult.Success();
        }


        public DomainResult SoftDelete(DateTime utcNow)
        {
            if (IsDeleted)
            {
                // Idempotent: deleting twice is still success
                return DomainResult.Success();
            }

            MarkDeleted(utcNow);
            IncrementVersion();
            return DomainResult.Success();
        }

        public DomainResult RestoreNote(DateTime utcNow)
        {
            if (!IsDeleted)
            {
                // Idempotent: restoring non-deleted is OK
                return DomainResult.Success();
            }

            Restore(utcNow);
            IncrementVersion();
            return DomainResult.Success();
        }

        /// <summary>
        /// Convenience helper for UI: derive a display title.
        /// (No side-effects, purely read-only.)
        /// </summary>
        public string GetDisplayTitle()
        {
            if (!string.IsNullOrWhiteSpace(Title))
            {
                return Title;
            }

            return "Untitled note";
        }

        // TODO : For Ai Later
        public DomainResult SetSummaryAndTags(string? summary, string? tags, DateTime utcNow)
        {
            if (IsDeleted)
            {
                return DomainResult.Failure(
                    new DomainError("Note.Deleted", "Cannot set summary on a deleted note.")
                );
            }

            Summary = summary;
            Tags = tags;
            IncrementVersion();
            Touch(utcNow);

            return DomainResult.Success();
        }

        private void IncrementVersion()
        {
            Version++;
        }
    }
}
